name: Update YouTube cards

on:
  schedule:
    - cron: "0 0 * * *"   # every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate YouTube Cards
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCCe6N1wD8E3lSVH4CMW88sQ
          max_videos: 6
          comment_tag_name: YOUTUBE-CARDS   # must match README markers

      - name: Commit if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update YouTube video cards"
          file_pattern: README.md
